/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OfficerLoginRouteImport } from './routes/officer_.login'
import { Route as OfficerInviteRouteImport } from './routes/officer_.invite'
import { Route as OfficerResolutionRouteImport } from './routes/officer.resolution'
import { Route as OfficerDashboardRouteImport } from './routes/officer.dashboard'
import { Route as AdminSignupRouteImport } from './routes/admin_.signup'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin_.forgot-password'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOfficersRouteImport } from './routes/admin.officers'
import { Route as AdminInviteRouteImport } from './routes/admin.invite'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAssignmentRouteImport } from './routes/admin.assignment'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppEscalationsRouteImport } from './routes/_app.escalations'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as OfficerComplaintsIndexRouteImport } from './routes/officer.complaints.index'
import { Route as AdminComplaintsIndexRouteImport } from './routes/admin.complaints.index'
import { Route as AppComplaintsIndexRouteImport } from './routes/_app.complaints.index'
import { Route as OfficerComplaintsIdRouteImport } from './routes/officer.complaints.$id'
import { Route as AdminComplaintsIdRouteImport } from './routes/admin.complaints.$id'
import { Route as AppComplaintsNewRouteImport } from './routes/_app.complaints.new'
import { Route as AppComplaintsIdRouteImport } from './routes/_app.complaints.$id'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OfficerLoginRoute = OfficerLoginRouteImport.update({
  id: '/officer_/login',
  path: '/officer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerInviteRoute = OfficerInviteRouteImport.update({
  id: '/officer_/invite',
  path: '/officer/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerResolutionRoute = OfficerResolutionRouteImport.update({
  id: '/resolution',
  path: '/resolution',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerDashboardRoute = OfficerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OfficerRoute,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin_/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin_/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfficersRoute = AdminOfficersRouteImport.update({
  id: '/officers',
  path: '/officers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentRoute = AdminAssignmentRouteImport.update({
  id: '/assignment',
  path: '/assignment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalationsRoute = AppEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const OfficerComplaintsIndexRoute = OfficerComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => OfficerRoute,
} as any)
const AdminComplaintsIndexRoute = AdminComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AdminRoute,
} as any)
const AppComplaintsIndexRoute = AppComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AppRoute,
} as any)
const OfficerComplaintsIdRoute = OfficerComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => OfficerRoute,
} as any)
const AdminComplaintsIdRoute = AdminComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AppComplaintsNewRoute = AppComplaintsNewRouteImport.update({
  id: '/complaints/new',
  path: '/complaints/new',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsIdRoute = AppComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/escalations': typeof AppEscalationsRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assignment': typeof AdminAssignmentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/resolution': typeof OfficerResolutionRoute
  '/officer/invite': typeof OfficerInviteRoute
  '/officer/login': typeof OfficerLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/complaints/$id': typeof AppComplaintsIdRoute
  '/complaints/new': typeof AppComplaintsNewRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
  '/complaints/': typeof AppComplaintsIndexRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
  '/officer/complaints/': typeof OfficerComplaintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/escalations': typeof AppEscalationsRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assignment': typeof AdminAssignmentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/resolution': typeof OfficerResolutionRoute
  '/officer/invite': typeof OfficerInviteRoute
  '/officer/login': typeof OfficerLoginRoute
  '/admin': typeof AdminIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/complaints/$id': typeof AppComplaintsIdRoute
  '/complaints/new': typeof AppComplaintsNewRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
  '/complaints': typeof AppComplaintsIndexRoute
  '/admin/complaints': typeof AdminComplaintsIndexRoute
  '/officer/complaints': typeof OfficerComplaintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/escalations': typeof AppEscalationsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assignment': typeof AdminAssignmentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin_/forgot-password': typeof AdminForgotPasswordRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin_/signup': typeof AdminSignupRoute
  '/officer/dashboard': typeof OfficerDashboardRoute
  '/officer/resolution': typeof OfficerResolutionRoute
  '/officer_/invite': typeof OfficerInviteRoute
  '/officer_/login': typeof OfficerLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/_app/complaints/$id': typeof AppComplaintsIdRoute
  '/_app/complaints/new': typeof AppComplaintsNewRoute
  '/admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/officer/complaints/$id': typeof OfficerComplaintsIdRoute
  '/_app/complaints/': typeof AppComplaintsIndexRoute
  '/admin/complaints/': typeof AdminComplaintsIndexRoute
  '/officer/complaints/': typeof OfficerComplaintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/officer'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/track'
    | '/verify-otp'
    | '/chat'
    | '/dashboard'
    | '/escalations'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/admin/analytics'
    | '/admin/assignment'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/invite'
    | '/admin/officers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/signup'
    | '/officer/dashboard'
    | '/officer/resolution'
    | '/officer/invite'
    | '/officer/login'
    | '/admin/'
    | '/officer/'
    | '/complaints/$id'
    | '/complaints/new'
    | '/admin/complaints/$id'
    | '/officer/complaints/$id'
    | '/complaints/'
    | '/admin/complaints/'
    | '/officer/complaints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/track'
    | '/verify-otp'
    | '/chat'
    | '/dashboard'
    | '/escalations'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/admin/analytics'
    | '/admin/assignment'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/invite'
    | '/admin/officers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/signup'
    | '/officer/dashboard'
    | '/officer/resolution'
    | '/officer/invite'
    | '/officer/login'
    | '/admin'
    | '/officer'
    | '/complaints/$id'
    | '/complaints/new'
    | '/admin/complaints/$id'
    | '/officer/complaints/$id'
    | '/complaints'
    | '/admin/complaints'
    | '/officer/complaints'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/admin'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/officer'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/track'
    | '/verify-otp'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/escalations'
    | '/_app/notifications'
    | '/_app/reports'
    | '/_app/settings'
    | '/admin/analytics'
    | '/admin/assignment'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/invite'
    | '/admin/officers'
    | '/admin/settings'
    | '/admin/users'
    | '/admin_/forgot-password'
    | '/admin_/login'
    | '/admin_/signup'
    | '/officer/dashboard'
    | '/officer/resolution'
    | '/officer_/invite'
    | '/officer_/login'
    | '/admin/'
    | '/officer/'
    | '/_app/complaints/$id'
    | '/_app/complaints/new'
    | '/admin/complaints/$id'
    | '/officer/complaints/$id'
    | '/_app/complaints/'
    | '/admin/complaints/'
    | '/officer/complaints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OfficerRoute: typeof OfficerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  TrackRoute: typeof TrackRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSignupRoute: typeof AdminSignupRoute
  OfficerInviteRoute: typeof OfficerInviteRoute
  OfficerLoginRoute: typeof OfficerLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/officer_/login': {
      id: '/officer_/login'
      path: '/officer/login'
      fullPath: '/officer/login'
      preLoaderRoute: typeof OfficerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer_/invite': {
      id: '/officer_/invite'
      path: '/officer/invite'
      fullPath: '/officer/invite'
      preLoaderRoute: typeof OfficerInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/resolution': {
      id: '/officer/resolution'
      path: '/resolution'
      fullPath: '/officer/resolution'
      preLoaderRoute: typeof OfficerResolutionRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/dashboard': {
      id: '/officer/dashboard'
      path: '/dashboard'
      fullPath: '/officer/dashboard'
      preLoaderRoute: typeof OfficerDashboardRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/admin_/signup': {
      id: '/admin_/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/forgot-password': {
      id: '/admin_/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/officers': {
      id: '/admin/officers'
      path: '/officers'
      fullPath: '/admin/officers'
      preLoaderRoute: typeof AdminOfficersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invite': {
      id: '/admin/invite'
      path: '/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignment': {
      id: '/admin/assignment'
      path: '/assignment'
      fullPath: '/admin/assignment'
      preLoaderRoute: typeof AdminAssignmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escalations': {
      id: '/_app/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof AppEscalationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/officer/complaints/': {
      id: '/officer/complaints/'
      path: '/complaints'
      fullPath: '/officer/complaints/'
      preLoaderRoute: typeof OfficerComplaintsIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/admin/complaints/': {
      id: '/admin/complaints/'
      path: '/complaints'
      fullPath: '/admin/complaints/'
      preLoaderRoute: typeof AdminComplaintsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/complaints/': {
      id: '/_app/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AppComplaintsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/officer/complaints/$id': {
      id: '/officer/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/officer/complaints/$id'
      preLoaderRoute: typeof OfficerComplaintsIdRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/admin/complaints/$id': {
      id: '/admin/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/admin/complaints/$id'
      preLoaderRoute: typeof AdminComplaintsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/complaints/new': {
      id: '/_app/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof AppComplaintsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/$id': {
      id: '/_app/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AppComplaintsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEscalationsRoute: typeof AppEscalationsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppComplaintsIdRoute: typeof AppComplaintsIdRoute
  AppComplaintsNewRoute: typeof AppComplaintsNewRoute
  AppComplaintsIndexRoute: typeof AppComplaintsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEscalationsRoute: AppEscalationsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppComplaintsIdRoute: AppComplaintsIdRoute,
  AppComplaintsNewRoute: AppComplaintsNewRoute,
  AppComplaintsIndexRoute: AppComplaintsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssignmentRoute: typeof AdminAssignmentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminInviteRoute: typeof AdminInviteRoute
  AdminOfficersRoute: typeof AdminOfficersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminComplaintsIdRoute: typeof AdminComplaintsIdRoute
  AdminComplaintsIndexRoute: typeof AdminComplaintsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssignmentRoute: AdminAssignmentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminInviteRoute: AdminInviteRoute,
  AdminOfficersRoute: AdminOfficersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminComplaintsIdRoute: AdminComplaintsIdRoute,
  AdminComplaintsIndexRoute: AdminComplaintsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OfficerRouteChildren {
  OfficerDashboardRoute: typeof OfficerDashboardRoute
  OfficerResolutionRoute: typeof OfficerResolutionRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerComplaintsIdRoute: typeof OfficerComplaintsIdRoute
  OfficerComplaintsIndexRoute: typeof OfficerComplaintsIndexRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerDashboardRoute: OfficerDashboardRoute,
  OfficerResolutionRoute: OfficerResolutionRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerComplaintsIdRoute: OfficerComplaintsIdRoute,
  OfficerComplaintsIndexRoute: OfficerComplaintsIndexRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OfficerRoute: OfficerRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  TrackRoute: TrackRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSignupRoute: AdminSignupRoute,
  OfficerInviteRoute: OfficerInviteRoute,
  OfficerLoginRoute: OfficerLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
